[tools]
usage = "latest"
node = "22"
python = "latest"
go = "latest"
deno = "latest"
lua = "latest"
rust = "latest"
rust-analyzer = "latest"
zig = "latest"
clang = "latest"
lazygit = "latest"
jq = "latest"
chezmoi = "latest"
yamllint = "latest"
ripgrep = "latest"
neovim = "latest"
lua-language-server = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
1password-cli = "latest"
