[tools]
usage = "latest"
node = "latest"
python = "latest"
go = "latest"
deno = "latest"
lua = "latest"
rust = "latest"
rust-analyzer = "latest"
zig = "latest"
clang = "latest"
lazygit = "latest"
jq = "latest"
chezmoi = "latest"
ripgrep = "latest"
neovim = "latest"
lua-language-server = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
clang-format = "latest"
tree-sitter = "latest"
shfmt = "latest"
shellcheck = "latest"
